version: '3.9'

services:
  status:
    build: ./status_service
    ports:
      - 8000:80
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/__health" ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 5s

  loyalty:
    build: ./loyalty_service
    ports:
      - 8001:80
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/__health" ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 5s

  krakend_ce:
    image: devopsfaith/krakend:watch
    volumes:
      - ./config/krakend:/etc/krakend
    ports:
      - "8080:8080"
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    depends_on:
      - status
      - loyalty

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8083:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    entrypoint: /opt/keycloak/bin/kc.sh start-dev

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    # networks:
    #   - jaeger-example

  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" 
  
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources


